// owasp-gen reads templates/owasp_agentic_2026.yaml and emits a Go file
// containing the TechniqueToAgenticCategories map. Used to keep the Go-side
// compliance lookup in sync with the canonical YAML mapping.
//
// Invoked via:
//
//	go run ./cmd/owasp-gen -yaml templates/owasp_agentic_2026.yaml -out src/compliance/owasp_agentic_generated.go
//
// Or via go generate: see src/compliance/gen.go.
//
// v0.9.0 status: the generator is functional but the existing hand-written
// map in owasp_agentic.go remains the runtime lookup. v0.10.0 will switch
// the lookup to use the generated map and add a CI no-diff check.
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// yamlSchema is the subset of templates/owasp_agentic_2026.yaml we read.
// We deliberately ignore fields the generator doesn't need (test_cases, etc.).
type yamlSchema struct {
	Categories map[string]struct {
		AttackTechniques []struct {
			ID string `yaml:"id"`
		} `yaml:"attack_techniques"`
	} `yaml:"categories"`
}

// asiToConst maps the YAML "ASIxx" key to the Go constant identifier
// declared in src/compliance/owasp_agentic.go.
var asiToConst = map[string]string{
	"ASI01": "AgentGoalHijack",
	"ASI02": "ToolMisuse",
	"ASI03": "PrivilegeAbuse",
	"ASI04": "AgenticSupplyChain",
	"ASI05": "UnexpectedCodeExecution",
	"ASI06": "MemoryPoisoning",
	"ASI07": "InsecureInterAgent",
	"ASI08": "CascadingFailures",
	"ASI09": "TrustExploitation",
	"ASI10": "RogueAgents",
}

func main() {
	yamlPath := flag.String("yaml", "templates/owasp_agentic_2026.yaml", "path to OWASP Agentic YAML")
	outPath := flag.String("out", "src/compliance/owasp_agentic_generated.go", "output Go file")
	flag.Parse()

	if err := run(*yamlPath, *outPath); err != nil {
		fmt.Fprintf(os.Stderr, "owasp-gen: %v\n", err)
		os.Exit(1)
	}
}

func run(yamlPath, outPath string) error {
	raw, err := os.ReadFile(yamlPath) // #nosec G304 -- yamlPath is operator-supplied via -yaml flag (build-time generator)
	if err != nil {
		return fmt.Errorf("read yaml %s: %w", yamlPath, err)
	}

	var doc yamlSchema
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parse yaml %s: %w", yamlPath, err)
	}

	// Build technique → []ASI ID map by walking categories.attack_techniques.
	techniqueToASI := map[string]map[string]bool{}
	for asi, cat := range doc.Categories {
		if _, known := asiToConst[asi]; !known {
			return fmt.Errorf("yaml has unknown ASI key %q (extend asiToConst in cmd/owasp-gen)", asi)
		}
		for _, t := range cat.AttackTechniques {
			if t.ID == "" {
				continue
			}
			if techniqueToASI[t.ID] == nil {
				techniqueToASI[t.ID] = map[string]bool{}
			}
			techniqueToASI[t.ID][asi] = true
		}
	}

	if len(techniqueToASI) == 0 {
		return fmt.Errorf("no techniques found in %s — yaml schema may have changed", yamlPath)
	}

	// Sort techniques and ASI IDs for deterministic output.
	techniques := make([]string, 0, len(techniqueToASI))
	for t := range techniqueToASI {
		techniques = append(techniques, t)
	}
	sort.Strings(techniques)

	src := emit(yamlPath, techniques, techniqueToASI)
	formatted, err := format.Source(src)
	if err != nil {
		// Surface the unformatted source on error to ease debugging.
		fmt.Fprintln(os.Stderr, string(src))
		return fmt.Errorf("format generated source: %w", err)
	}

	if err := os.WriteFile(outPath, formatted, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("owasp-gen: wrote %d techniques to %s\n", len(techniques), outPath)
	return nil
}

func emit(yamlPath string, techniques []string, m map[string]map[string]bool) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/owasp-gen from %s; DO NOT EDIT.\n", yamlPath)
	fmt.Fprintf(&b, "// Generated at %s.\n", time.Now().UTC().Format(time.RFC3339))
	b.WriteString("\n")
	b.WriteString("package compliance\n\n")
	b.WriteString("// GeneratedTechniqueToAgenticCategories is the build-derived counterpart of\n")
	b.WriteString("// the hand-written TechniqueToAgenticCategories. v0.9.0 ships both side-by-side;\n")
	b.WriteString("// v0.10.0 will switch the lookup to use this map exclusively.\n")
	b.WriteString("var GeneratedTechniqueToAgenticCategories = map[string][]OWASPAgenticCategory{\n")

	for _, t := range techniques {
		asis := make([]string, 0, len(m[t]))
		for a := range m[t] {
			asis = append(asis, a)
		}
		sort.Strings(asis)

		consts := make([]string, len(asis))
		for i, a := range asis {
			consts[i] = asiToConst[a]
		}
		fmt.Fprintf(&b, "\t%q: {%s},\n", t, strings.Join(consts, ", "))
	}

	b.WriteString("}\n")
	return []byte(b.String())
}
