package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGeneratorAgainstFixture runs the generator against a small inline YAML
// fixture and checks the emitted Go file for expected entries and shape.
// Does not depend on the real templates/owasp_agentic_2026.yaml so the test
// stays stable when that file changes.
func TestGeneratorAgainstFixture(t *testing.T) {
	dir := t.TempDir()
	yamlPath := filepath.Join(dir, "fixture.yaml")
	outPath := filepath.Join(dir, "out.go")

	fixture := `framework:
  name: "test"
  version: "fixture"

categories:
  ASI01:
    name: "Agent Goal Hijack"
    attack_techniques:
      - id: minja
        priority: high
      - id: shared_tech
        priority: medium
  ASI06:
    name: "Memory Poisoning"
    attack_techniques:
      - id: memorygraft
        priority: high
      - id: shared_tech
        priority: low
`
	if err := os.WriteFile(yamlPath, []byte(fixture), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}

	if err := run(yamlPath, outPath); err != nil {
		t.Fatalf("run() returned error: %v", err)
	}

	got, err := os.ReadFile(outPath) //nolint:gosec // path under TempDir
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	src := string(got)

	// Header.
	if !strings.Contains(src, "Code generated by cmd/owasp-gen") {
		t.Errorf("output missing generated-code header")
	}
	if !strings.Contains(src, "DO NOT EDIT") {
		t.Errorf("output missing DO NOT EDIT marker")
	}
	if !strings.Contains(src, "package compliance") {
		t.Errorf("output missing package declaration")
	}

	// Each technique should appear with the expected ASI constants.
	cases := []struct {
		key  string
		want []string // substrings expected on the line
	}{
		{`"minja":`, []string{"AgentGoalHijack"}},
		{`"memorygraft":`, []string{"MemoryPoisoning"}},
		{`"shared_tech":`, []string{"AgentGoalHijack", "MemoryPoisoning"}}, // sorted ASI keys → constants
	}
	for _, c := range cases {
		idx := strings.Index(src, c.key)
		if idx < 0 {
			t.Errorf("output missing entry for %s", c.key)
			continue
		}
		// Take to end of that line.
		nl := strings.Index(src[idx:], "\n")
		line := src[idx : idx+nl]
		for _, want := range c.want {
			if !strings.Contains(line, want) {
				t.Errorf("entry %s missing %q (got line: %s)", c.key, want, line)
			}
		}
	}
}

func TestGeneratorRejectsUnknownASIKey(t *testing.T) {
	dir := t.TempDir()
	yamlPath := filepath.Join(dir, "fixture.yaml")
	outPath := filepath.Join(dir, "out.go")

	fixture := `categories:
  ASI99:
    name: "Bogus"
    attack_techniques:
      - id: foo
`
	_ = os.WriteFile(yamlPath, []byte(fixture), 0o644)

	err := run(yamlPath, outPath)
	if err == nil {
		t.Fatal("expected error on unknown ASI key, got nil")
	}
	if !strings.Contains(err.Error(), "unknown ASI key") {
		t.Errorf("expected unknown-ASI error, got: %v", err)
	}
}

func TestGeneratorRejectsEmptyYaml(t *testing.T) {
	dir := t.TempDir()
	yamlPath := filepath.Join(dir, "fixture.yaml")
	outPath := filepath.Join(dir, "out.go")

	_ = os.WriteFile(yamlPath, []byte(`categories: {}`), 0o644)

	err := run(yamlPath, outPath)
	if err == nil {
		t.Fatal("expected error on empty yaml, got nil")
	}
	if !strings.Contains(err.Error(), "no techniques found") {
		t.Errorf("expected no-techniques error, got: %v", err)
	}
}
