# GitHub Pages Configuration for LLMrecon
title: LLMrecon - Advanced LLM Security Testing Framework
description: Enterprise-grade security testing for Large Language Models with OWASP Top 10 2025 compliance
baseurl: "/LLMrecon"
url: "https://perplext.github.io"

# Theme (using default GitHub Pages theme)
theme: null

# Exclude files from build
exclude:
  - "*.go"
  - "*.py"
  - "go.mod"
  - "go.sum"
  - "requirements.txt"
  - "Makefile"

# Include specific files
include:
  - "index.html"
  - "*.md"
  - "*.html"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Default values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      
# Plugins (if using Jekyll plugins)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag