name: Claude Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  pass:
    name: Pass
    runs-on: ubuntu-latest
    steps:
      - name: Skip Code Review
        run: echo "Code review temporarily disabled to allow dependency updates"